//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTPSInstrument : NSObject
{
    NSString *_instrumentID;
    int _index;
    NSDictionary *_localOptions;
    double _startTime_secSince1970;
    double _stopTime_secSince1970;
    unsigned long long _startTime_Mach;
    unsigned long long _stopTime_Mach;
    unsigned int _machTimeBaseNumer;
    unsigned int _machTimeBaseDenom;
    DTTap *_tap;
    BOOL _useTap;
    DTKTraceTapConfig *_tapConfig;
    NSMutableArray *_triggerIndices;
    NSMutableArray *_triggerConfigPlistArray;
    int _startCount;
    BOOL _dirty;
    BOOL _alreadyPrepared;
    DTPerformanceSession *_parentSession;
    BOOL _requiresKTrace;
    BOOL _dummyInstrument;
    DTPSService *_service;
    NSURL *_serializedTmpMessageURL;
    long long _serviceVersion;
}

+ (BOOL)instrumentIDRequiresKTrace:(id)arg1;
@property(readonly, nonatomic) long long serviceVersion; // @synthesize serviceVersion=_serviceVersion;
@property(retain, nonatomic) NSURL *serializedTmpMessageURL; // @synthesize serializedTmpMessageURL=_serializedTmpMessageURL;
@property(retain, nonatomic) DTPSService *service; // @synthesize service=_service;
@property(readonly, nonatomic) BOOL dummyInstrument; // @synthesize dummyInstrument=_dummyInstrument;
@property(readonly, nonatomic) BOOL requiresKTrace; // @synthesize requiresKTrace=_requiresKTrace;
@property(retain, nonatomic) NSDictionary *localOptions; // @synthesize localOptions=_localOptions;
- (void).cxx_destruct;
- (BOOL)writeToFile:(id)arg1;
- (id)messageQueueFileName;
- (id)dataFileName;
- (id)finalSymbolicatorSignatures;
- (BOOL)end;
- (BOOL)stop;
- (BOOL)start;
- (BOOL)prepare;
- (id)tapConfiguration:(id)arg1;
- (id)triggerConfiguration:(id)arg1;
- (BOOL)isDirty;
- (BOOL)isRecording;
- (void)recordStopTime;
- (BOOL)recordStartTime;
- (id)session;
@property(readonly, retain, nonatomic) DTKTraceTapConfig *tapConfig;
- (int)index;
- (id)instrumentID;
- (void)clearState;
- (id)configure:(id)arg1;
- (void)dealloc;
- (id)initWithID:(id)arg1 index:(int)arg2 options:(id)arg3 parent:(id)arg4;

@end