//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface _IDENavigableItemPredicateFilter : IDENavigableItemFilter
{
    NSPredicate *_predicate;
}

@property(readonly) NSPredicate *predicate; // @synthesize predicate=_predicate;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)matchesNavigableItem:(id)arg1;
- (id)_initWithPredicate:(id)arg1;

@end