//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol IDECoverage_Method <NSObject, IDECoverage_Base>
@property(readonly, copy, nonatomic) NSImage *ide_coverage_image;
@property(readonly, nonatomic) unsigned long long ide_coverage_devicesCount;
@end