//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEComponentsToolchainsTableController : IDEViewController <NSTableViewDelegate, NSMenuDelegate>
{
    IDEComponentsToolchainsTableRowItem *_contextItem;
    DVTToolchainRegistry *_toolchainRegistry;
    NSArray *_items;
    DVTTableView *_tableView;
    NSScrollView *_tableScrollView;
    DVTBorderedView *_tableBorderedView;
}

@property(retain) DVTBorderedView *tableBorderedView; // @synthesize tableBorderedView=_tableBorderedView;
@property(retain) NSScrollView *tableScrollView; // @synthesize tableScrollView=_tableScrollView;
@property(retain) DVTTableView *tableView; // @synthesize tableView=_tableView;
@property(retain) NSArray *items; // @synthesize items=_items;
@property(retain) DVTToolchainRegistry *toolchainRegistry; // @synthesize toolchainRegistry=_toolchainRegistry;
- (void).cxx_destruct;
- (void)showContext:(id)arg1;
- (void)_verifyCodeSignature:(id)arg1;
- (void)_moveToTrash:(id)arg1;
- (void)_revealInFinder:(id)arg1;
- (void)switchToToolchain:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)toolchainItemForContextAction;
- (id)itemAtIndex:(long long)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end