//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEToolchainsMenuItem : NSMenuItem
{
    DVTObservingToken *_observingToken;
    DVTToolchainRegistry *_registry;
}

- (void).cxx_destruct;
- (void)_selectToolchain:(id)arg1;
- (void)_manage:(id)arg1;
- (void)_update;
- (id)_menuItemForToolchain:(id)arg1;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 action:(SEL)arg2 keyEquivalent:(id)arg3;
- (id)initWithRegistry:(id)arg1;

@end