//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XRFrameActivity : NSObject
{
    id <XRFrameActivityManager> _manager;
    BOOL _yielded;
    NSString *_activityName;
    const char *_shouldYield;
    NSOperation *_completionSignal;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(readonly, nonatomic) NSOperation *completionSignal; // @synthesize completionSignal=_completionSignal;
@property(readonly, nonatomic, getter=didYield) BOOL yielded; // @synthesize yielded=_yielded;
@property(readonly, nonatomic) const char *shouldYield; // @synthesize shouldYield=_shouldYield;
@property(retain, nonatomic) NSString *activityName; // @synthesize activityName=_activityName;
- (void).cxx_destruct;
- (void)yield;
- (id)init;
- (id)initWithManager:(id)arg1;

@end