//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTDeveloperAccountCredentialsManager : NSObject
{
    struct OpaqueSecKeychainRef *_keychain;
}

+ (id)defaultAccountCredentialsManager;
@property struct OpaqueSecKeychainRef *keychain; // @synthesize keychain=_keychain;
- (BOOL)deleteCredential:(id)arg1 error:(id *)arg2;
- (id)accountCredentialsFromUsername:(id)arg1 alternateDSID:(id)arg2 token:(id)arg3 successfullyPersisted:(char *)arg4 error:(id *)arg5;
- (id)accountCredentialsFromUsername:(id)arg1 password:(id)arg2 successfullyPersisted:(char *)arg3 error:(id *)arg4;
- (id)accountCredentialsFromCredentials:(id)arg1 withPassword:(id)arg2 successfullyPersisted:(char *)arg3 error:(id *)arg4;
- (id)accountCredentialsForUsername:(id)arg1 error:(id *)arg2;
- (id)initWithKeychain:(struct OpaqueSecKeychainRef *)arg1;

@end