//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTLaunchWithToolchainConfiguration : NSObject
{
    NSDictionary *_environment;
    NSDictionary *_userDefaults;
    NSDictionary *_buildSettings;
}

+ (id)configurationForToolchain:(id)arg1 error:(id *)arg2;
+ (id)configurationForReLaunchWithoutToolchainOverride;
@property(readonly) NSDictionary *buildSettings; // @synthesize buildSettings=_buildSettings;
@property(readonly) NSDictionary *userDefaults; // @synthesize userDefaults=_userDefaults;
@property(readonly) NSDictionary *environment; // @synthesize environment=_environment;
- (void).cxx_destruct;
- (id)description;
@property(readonly) NSString *buildSettingsXcconfigRepresentation;

@end