//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTLaunchWithToolchain : NSObject
{
}

+ (BOOL)relaunchXcodeIfNeededUsingXcconfig:(BOOL)arg1 userDefaultsPassingStyle:(int)arg2 error:(id *)arg3;
+ (BOOL)relaunchXcodeIfNeededShowingUI:(BOOL)arg1 error:(id *)arg2;
+ (BOOL)relaunchXcodeIfNeededUsingXcconfig:(BOOL)arg1 userDefaultsPassingStyle:(int)arg2 showingUI:(BOOL)arg3 error:(id *)arg4;
+ (void)finishedCrashCheck;
+ (BOOL)runCrashCheckFlowForToolchain:(id)arg1 error:(id *)arg2;
+ (BOOL)runVerificationFlowForToolchain:(id)arg1 showingUI:(BOOL)arg2 error:(id *)arg3;
+ (BOOL)verifySignatureRevocationStatusForPath:(id)arg1 error:(id *)arg2;
+ (void)setIntendedDefaultToolchainOverride:(id)arg1;
+ (id)intendedDefaultToolchainOverridePath;
+ (id)intendedDefaultToolchainOverrideSpec;
+ (id)intendedDefaultToolchainOverrideSpecifier;
+ (id)defaultToolchainOverrideSpecifier;
+ (BOOL)launchWithConfiguration:(id)arg1 error:(id *)arg2;
+ (BOOL)launchWithConfiguration:(id)arg1 usingXcconfig:(BOOL)arg2 userDefaultsPassingStyle:(int)arg3 error:(id *)arg4;

@end