//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTNSRunLoopLatencyCheckerToken : NSObject
{
    BOOL _cancelled;
    BOOL _isPerformWithObject;
    id _target;
    id _argument;
    SEL _selector;
    DVTStackBacktrace *_creationBacktrace;
    NSRunLoop *_runLoop;
}

@property(retain) NSRunLoop *runLoop; // @synthesize runLoop=_runLoop;
@property(retain) DVTStackBacktrace *creationBacktrace; // @synthesize creationBacktrace=_creationBacktrace;
@property BOOL isPerformWithObject; // @synthesize isPerformWithObject=_isPerformWithObject;
@property BOOL cancelled; // @synthesize cancelled=_cancelled;
@property SEL selector; // @synthesize selector=_selector;
@property(retain) id argument; // @synthesize argument=_argument;
@property(retain) id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (id)description;

@end