//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSObject (DVTNSRunLoopLatencyChecker)
+ (void)_DVTNSRunLoopLatencyChecker_cancelPreviousPerformRequestsWithTarget:(id)arg1;
+ (void)_DVTNSRunLoopLatencyChecker_cancelPreviousPerformRequestsWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
- (void)_DVTNSRunLoopLatencyChecker_performSelector:(SEL)arg1 withObject:(id)arg2 afterDelay:(double)arg3 inModes:(id)arg4;
- (void)_DVTNSRunLoopLatencyChecker_performSelectorWithToken:(id)arg1;
@end