//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSRunLoop (DVTNSRunLoopLatencyChecker)
- (void)_DVTNSRunLoopLatencyChecker_cancelPerformSelectorsWithTarget:(id)arg1;
- (void)_DVTNSRunLoopLatencyChecker_cancelPerformSelector:(SEL)arg1 target:(id)arg2 argument:(id)arg3;
- (void)_DVTNSRunLoopLatencyChecker_performSelector:(SEL)arg1 target:(id)arg2 argument:(id)arg3 order:(unsigned long long)arg4 modes:(id)arg5;
@end