//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTPortalCSR : NSObject
{
    NSString *_portalCertificateID;
}

+ (id)createCertificateWithSession:(id)arg1 team:(id)arg2 type:(id)arg3 csrData:(id)arg4 error:(id *)arg5;
+ (id)createCertificateWithSession:(id)arg1 team:(id)arg2 type:(id)arg3 keyName:(id)arg4 privateKey:(struct OpaqueSecKeyRef **)arg5 error:(id *)arg6;
@property(readonly, copy, nonatomic) NSString *portalCertificateID; // @synthesize portalCertificateID=_portalCertificateID;
- (void).cxx_destruct;
- (id)description;

@end