//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTPortalCreateProfileService : DVTPortalService
{
}

+ (id)createProfileServiceWithTeam:(id)arg1 profileType:(id)arg2 platform:(id)arg3 appID:(id)arg4 name:(id)arg5 certificates:(id)arg6;

@end