//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTPortalProfileType : NSObject
{
    BOOL _teamProfile;
    BOOL _enterpriseOnly;
    BOOL _canBeCreatedByMembers;
    BOOL _canBeCreatedByEnterpriseTeams;
    BOOL _canBeCreatedByUniversityTeams;
    BOOL _canBeCreatedByFreeTeams;
    NSString *_identifier;
    DVTPortalCertificateType *_certificateType;
    DVTPortalProfilePurpose *_purpose;
    NSString *_namePostfix;
    DVTPortalPlatform *_portalPlatform;
    long long _devicesStyle;
}

+ (id)profileTypeWithIdentifier:(id)arg1;
+ (id)profileTypes;
@property(readonly, nonatomic) long long devicesStyle; // @synthesize devicesStyle=_devicesStyle;
@property(readonly, nonatomic) BOOL canBeCreatedByFreeTeams; // @synthesize canBeCreatedByFreeTeams=_canBeCreatedByFreeTeams;
@property(readonly, nonatomic) BOOL canBeCreatedByUniversityTeams; // @synthesize canBeCreatedByUniversityTeams=_canBeCreatedByUniversityTeams;
@property(readonly, nonatomic) BOOL canBeCreatedByEnterpriseTeams; // @synthesize canBeCreatedByEnterpriseTeams=_canBeCreatedByEnterpriseTeams;
@property(readonly, nonatomic) BOOL canBeCreatedByMembers; // @synthesize canBeCreatedByMembers=_canBeCreatedByMembers;
@property(readonly, nonatomic, getter=isEnterpriseOnly) BOOL enterpriseOnly; // @synthesize enterpriseOnly=_enterpriseOnly;
@property(readonly, nonatomic) DVTPortalPlatform *portalPlatform; // @synthesize portalPlatform=_portalPlatform;
@property(readonly, nonatomic) NSString *namePostfix; // @synthesize namePostfix=_namePostfix;
@property(readonly, nonatomic) DVTPortalProfilePurpose *purpose; // @synthesize purpose=_purpose;
@property(readonly, nonatomic, getter=isTeamProfile) BOOL teamProfile; // @synthesize teamProfile=_teamProfile;
@property(readonly, nonatomic) DVTPortalCertificateType *certificateType; // @synthesize certificateType=_certificateType;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) DVTPlatform *platform;
- (id)description;
- (id)initWithIdentifier:(id)arg1 portalPlatform:(id)arg2 certificateType:(id)arg3 isTeamProfile:(BOOL)arg4 purpose:(id)arg5 enterpriseOnly:(BOOL)arg6 canBeCreatedByMembers:(BOOL)arg7 canBeCreatedByEnterpriseTeams:(BOOL)arg8 canBeCreatedByUniversityTeams:(BOOL)arg9 canBeCreatedByFreeTeams:(BOOL)arg10 devicesStyle:(long long)arg11 namePostfix:(id)arg12;

@end