//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DVTPortalProfile : NSObject
{
    BOOL _teamProfile;
    NSData *_profileData;
    NSString *_name;
    NSString *_managingApp;
    DVTPlatform *_platform;
    NSString *_portalSubPlatform;
    DVTPortalAppID *_appID;
    DVTPortalTeam *_team;
    NSString *_portalID;
    NSString *_UUID;
    DVTPortalProgram *_portalProgram;
}

+ (id)_deleteProfileServiceWithTeam:(id)arg1 program:(id)arg2 profile:(id)arg3;
+ (id)_downloadProfileServiceWithPortalID:(id)arg1 team:(id)arg2 program:(id)arg3;
+ (id)_existingAppIDMatchingBundleID:(id)arg1 requiresExplicitAppID:(BOOL)arg2 candidateAppIDs:(id)arg3;
+ (BOOL)_existingAppIDMatchingBundleID:(id)arg1 requiresExplicitAppID:(BOOL)arg2 team:(id)arg3 platform:(id)arg4 session:(id)arg5 matchingAppID:(id *)arg6 error:(id *)arg7;
+ (BOOL)_requiresExplicitAppIDForFeatures:(id)arg1;
+ (BOOL)_updateContainersForAppID:(id)arg1 withCharacteristics:(id)arg2 session:(id)arg3 error:(id *)arg4;
+ (id)_preparedAppIDWithCharacteristics:(id)arg1 session:(id)arg2 error:(id *)arg3;
+ (id)_errorForPermissionsFailure;
+ (id)_errorForNoCertificates;
+ (id)_errorForNoDevicesWithUnderlyingError:(id)arg1;
+ (id)_profileMatchingName:(id)arg1 session:(id)arg2 team:(id)arg3 profileType:(id)arg4 error:(id *)arg5;
+ (BOOL)_deletePreExistingProfileForType:(id)arg1 name:(id)arg2 session:(id)arg3 team:(id)arg4 error:(id *)arg5;
+ (id)_certificatesForProfileType:(id)arg1 session:(id)arg2 team:(id)arg3 error:(id *)arg4;
+ (id)_createAndDownloadNonTeamProvisioningProfileWithTeam:(id)arg1 session:(id)arg2 profileType:(id)arg3 platform:(id)arg4 appID:(id)arg5 error:(id *)arg6;
+ (id)_downloadTeamProfileServiceWithTeam:(id)arg1 platform:(id)arg2 appID:(id)arg3;
+ (id)_requestProfileWithAppID:(id)arg1 type:(id)arg2 team:(id)arg3 platform:(id)arg4 session:(id)arg5 error:(id *)arg6;
+ (id)createProfileWithSession:(id)arg1 characteristics:(id)arg2 error:(id *)arg3;
+ (id)_listProfilesServiceWithTeam:(id)arg1 platform:(id)arg2;
+ (id)profilesWithSession:(id)arg1 team:(id)arg2 platform:(id)arg3 error:(id *)arg4;
@property(retain, nonatomic) DVTPortalProgram *portalProgram; // @synthesize portalProgram=_portalProgram;
@property(copy, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(copy, nonatomic) NSString *portalID; // @synthesize portalID=_portalID;
@property(retain, nonatomic) DVTPortalTeam *team; // @synthesize team=_team;
@property(retain, nonatomic) DVTPortalAppID *appID; // @synthesize appID=_appID;
@property(copy, nonatomic) NSString *portalSubPlatform; // @synthesize portalSubPlatform=_portalSubPlatform;
@property(retain, nonatomic) DVTPlatform *platform; // @synthesize platform=_platform;
@property(copy, nonatomic) NSString *managingApp; // @synthesize managingApp=_managingApp;
@property(nonatomic, getter=isTeamProfile) BOOL teamProfile; // @synthesize teamProfile=_teamProfile;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSData *profileData; // @synthesize profileData=_profileData;
- (void).cxx_destruct;
- (BOOL)removeWithSession:(id)arg1 error:(id *)arg2;
- (BOOL)downloadWithSession:(id)arg1 error:(id *)arg2;
- (id)description;

@end