//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTKTraceTapMessageHandler : DTTapMessageHandler
{
    BOOL _isSessionBased;
    id <DTKPDatastream> _datastream;
    NSMutableArray *_rawBufferAccumulator;
    unsigned int _tapVersion;
    unsigned int _coreCount;
    long long _triggerCount;
    unsigned int *_triggerIDs;
    NSMutableArray *_metadataByTriggerIndex;
    unsigned int _containersCreated;
    struct DTKTraceTapContainerArray _containers;
    struct __CFArray *_partialContainersByTrigger;
}

- (void).cxx_destruct;
- (id)messageReceived:(id)arg1;
- (id)initWithConfig:(id)arg1 requiresSession:(BOOL)arg2;

@end