//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface DTTapMemo : NSObject
{
    BOOL _moreData;
    BOOL _supportsPeek;
    BOOL _finalMemo;
    unsigned int _tapVersion;
}

@property(nonatomic) BOOL finalMemo; // @synthesize finalMemo=_finalMemo;
@property(nonatomic) BOOL supportsPeek; // @synthesize supportsPeek=_supportsPeek;
@property(nonatomic) BOOL moreData; // @synthesize moreData=_moreData;
@property(nonatomic) unsigned int tapVersion; // @synthesize tapVersion=_tapVersion;

@end