//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@protocol DTTapMemoHandlerDelegate <NSObject>
- (void)sendMemo:(DTTapMemo *)arg1 toClientUsingConfig:(DTTapConfig *)arg2;
- (void)sendMemo:(DTTapMemo *)arg1 toBulkReceiver:(id <DTTapBulkDataReceiver>)arg2;

@optional
- (NSDictionary *)peekAtMemo:(DTTapMemo *)arg1;
@end