//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XCSUIIntegrationEditor_SummaryTab_StatusView : NSTableCellView
{
    XCSBuildResultSummary *_buildResultSummary;
}

@property(retain, nonatomic) XCSBuildResultSummary *buildResultSummary; // @synthesize buildResultSummary=_buildResultSummary;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setNeedsDisplay:(BOOL)arg1;
- (void)drawBadges:(id)arg1 inWidth:(double)arg2 firstBadgeViewFrame:(struct CGRect)arg3 badgeViewFrames:(struct CGRect *)arg4;
- (id)badgeImagesHasErrors:(BOOL)arg1 warnings:(BOOL)arg2 analysis:(BOOL)arg3 ranTests:(BOOL)arg4 ranPerf:(BOOL)arg5 testsPassed:(BOOL)arg6 perfPassed:(BOOL)arg7;
- (void)buildBarWithErrorColor:(id)arg1 errorCount:(unsigned long long)arg2 errorChange:(unsigned long long)arg3 warningColor:(id)arg4 warningCount:(unsigned long long)arg5 warningChange:(unsigned long long)arg6 analysisColor:(id)arg7 analysisCount:(unsigned long long)arg8 analyzerWarningChange:(unsigned long long)arg9 testsColor:(id)arg10 testsCount:(unsigned long long)arg11 testsChange:(unsigned long long)arg12 perfColor:(id)arg13 perfCount:(unsigned long long)arg14 perfImproved:(unsigned long long)arg15 perfRegressed:(unsigned long long)arg16 badgeFrames:(struct CGRect *)arg17 hostWidth:(double)arg18 iBarFrame:(struct CGRect)arg19;
- (void)reconfigureBadge;
- (void)layout;

@end