//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XCSUIBotDefinition_SchedulingEditor : IDEViewController <NSControlTextEditingDelegate>
{
    XCSUIBotDefinitionContext *_botDefinitionContext;
    NSView *_mainView;
    NSView *_scheduleLayer;
    NSPopUpButton *_scheduleTypePopUp;
    NSView *_periodicLayer;
    NSPopUpButton *_periodTypePopUp;
    NSPopUpButton *_minutePopUp;
    NSTextField *_onLabel;
    NSPopUpButton *_dayOfWeekPopUp;
    NSDatePicker *_timePicker;
    NSTextField *_minutesAfterTheHourLabel;
    NSTextField *_atLabel;
    NSView *_onCommitLayer;
    NSView *_manualLayer;
    unsigned long long _currentScheduleType;
    unsigned long long _currentPeriodType;
}

+ (id)keyPathsForValuesAffectingTimeOfDayToIntegrate;
+ (id)keyPathsForValuesAffectingCreateBotAssistantContext;
+ (id)keyPathsForValuesAffectingAssistantContext;
@property(nonatomic) unsigned long long currentPeriodType; // @synthesize currentPeriodType=_currentPeriodType;
@property(nonatomic) unsigned long long currentScheduleType; // @synthesize currentScheduleType=_currentScheduleType;
@property(retain, nonatomic) NSView *manualLayer; // @synthesize manualLayer=_manualLayer;
@property(retain, nonatomic) NSView *onCommitLayer; // @synthesize onCommitLayer=_onCommitLayer;
@property(retain, nonatomic) NSTextField *atLabel; // @synthesize atLabel=_atLabel;
@property(retain, nonatomic) NSTextField *minutesAfterTheHourLabel; // @synthesize minutesAfterTheHourLabel=_minutesAfterTheHourLabel;
@property(retain, nonatomic) NSDatePicker *timePicker; // @synthesize timePicker=_timePicker;
@property(retain, nonatomic) NSPopUpButton *dayOfWeekPopUp; // @synthesize dayOfWeekPopUp=_dayOfWeekPopUp;
@property(retain, nonatomic) NSTextField *onLabel; // @synthesize onLabel=_onLabel;
@property(retain, nonatomic) NSPopUpButton *minutePopUp; // @synthesize minutePopUp=_minutePopUp;
@property(retain, nonatomic) NSPopUpButton *periodTypePopUp; // @synthesize periodTypePopUp=_periodTypePopUp;
@property(retain, nonatomic) NSView *periodicLayer; // @synthesize periodicLayer=_periodicLayer;
@property(retain, nonatomic) NSPopUpButton *scheduleTypePopUp; // @synthesize scheduleTypePopUp=_scheduleTypePopUp;
@property(retain, nonatomic) NSView *scheduleLayer; // @synthesize scheduleLayer=_scheduleLayer;
@property(retain, nonatomic) NSView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) XCSUIBotDefinitionContext *botDefinitionContext; // @synthesize botDefinitionContext=_botDefinitionContext;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *timeOfDayToIntegrate;
- (void)minutePopUpAction:(id)arg1;
- (void)commitTypeAction:(id)arg1;
- (id)preparePeriodicLayer;
- (void)periodTypePopUpAction:(id)arg1;
- (void)_updateMinutePopUpIndex;
- (void)prepareLayers;
- (void)scheduleTypePopUpAction:(id)arg1;
- (void)moveView:(id)arg1 rightOfView:(id)arg2 withPadding:(unsigned long long)arg3;
- (void)moveView:(id)arg1 belowView:(id)arg2;
- (void)addLayerToEnd:(id)arg1 belowView:(id)arg2;
- (void)setupLayers;
- (id)createBotAssistantContext;
- (id)assistantContext;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end