//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEProvisioningProfileImpl : NSObject <IDEProvisioningProfile, IDEProvisioningLocalProfileState, NSCoding>
{
    NSObject<DVTProvisioningProfileDataSource> *_dataSource;
    DVTFilePath *_filePath;
    NSString *_bundleIdentifier;
    NSString *_identifier;
    NSString *_name;
    NSDate *_expirationDate;
    NSString *_portalPlatformIdentifier;
    NSDictionary *_entitlements;
    NSString *_teamIdentifier;
    NSString *_teamName;
    DVTPlatform *_dvt_platform;
    id <IDEProvisioningTeam> _team;
    BOOL _isCachedCopy;
}

@property(readonly) BOOL isCachedCopy; // @synthesize isCachedCopy=_isCachedCopy;
- (void).cxx_destruct;
- (id)_dvt_platform;
- (BOOL)_isMacProfile;
- (id)entitlements;
- (id)teamName;
@property(readonly, nonatomic) NSString *teamIdentifier;
@property(readonly, nonatomic) NSString *bundleIdentifier;
@property(readonly, nonatomic) DVTFilePath *filePath;
@property(readonly, nonatomic) NSString *portalSubPlatformIdentifier;
@property(readonly, nonatomic) NSString *portalPlatformIdentifier;
@property(readonly, nonatomic) NSDate *expirationDate;
- (BOOL)isTeamProfile;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *identifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithFilePath:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end