//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDEPlaygroundPageSharedContext : IDEPlaygroundCommonSharedContext
{
    IDEPlaygroundSharedContext *_playgroundContext;
}

+ (id)keyPathsForValuesAffectingSwiftContentsFilePath;
+ (id)keyPathsForValuesAffectingImplicit;
+ (Class)contextDeserializerClass;
+ (Class)contextSerializerClass;
+ (id)filePathExtension;
+ (id)UTI;
@property(readonly, nonatomic) __weak IDEPlaygroundSharedContext *playgroundContext; // @synthesize playgroundContext=_playgroundContext;
- (void).cxx_destruct;
@property(readonly, nonatomic) DVTFilePath *swiftContentsFilePath;
- (id)_targetTripleForAuxiliarySource;
- (id)_sdkForAuxiliarySource;
- (id)auxiliarySourceFrameworkDependencies;
- (id)sourcesDirectoryPath;
- (id)resourcesDirectoryPath;
- (id)name;
- (id)description;

// Remaining properties
@property(readonly, nonatomic) DVTFilePath *timelineFilePath; // @dynamic timelineFilePath;

@end