//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IDETestingDiagnosticLogArbiter : NSObject
{
    id <IDETestingDiagnosticLogWriter> _writer;
    unsigned long long _state;
    NSMutableArray *_buffers;
    NSMutableData *_currentBuffer;
    unsigned long long _maxLoggedBytes;
    unsigned long long _maxBufferedBytes;
    double _contextInterval;
    unsigned long long _totalBytesLogged;
    unsigned long long _totalBytesBuffered;
    NSTimer *_rotationTimer;
    unsigned long long _bufferedMessages;
    unsigned long long _bufferedMessagesInCurrentBuffer;
}

@property unsigned long long bufferedMessagesInCurrentBuffer; // @synthesize bufferedMessagesInCurrentBuffer=_bufferedMessagesInCurrentBuffer;
@property unsigned long long bufferedMessages; // @synthesize bufferedMessages=_bufferedMessages;
@property(retain) NSTimer *rotationTimer; // @synthesize rotationTimer=_rotationTimer;
@property unsigned long long totalBytesBuffered; // @synthesize totalBytesBuffered=_totalBytesBuffered;
@property unsigned long long totalBytesLogged; // @synthesize totalBytesLogged=_totalBytesLogged;
@property double contextInterval; // @synthesize contextInterval=_contextInterval;
@property unsigned long long maxBufferedBytes; // @synthesize maxBufferedBytes=_maxBufferedBytes;
@property unsigned long long maxLoggedBytes; // @synthesize maxLoggedBytes=_maxLoggedBytes;
@property(retain) NSMutableData *currentBuffer; // @synthesize currentBuffer=_currentBuffer;
@property(retain) NSMutableArray *buffers; // @synthesize buffers=_buffers;
@property unsigned long long state; // @synthesize state=_state;
@property __weak id <IDETestingDiagnosticLogWriter> writer; // @synthesize writer=_writer;
- (void).cxx_destruct;
- (void)finishLogging;
- (void)flushBufferedMessages;
- (void)dumpBuffersPreservingContextInterval;
- (void)startBuffering;
- (void)startLogging;
- (void)_flushBuffers;
- (void)_rotateBuffers;
- (void)_writeData:(id)arg1;
- (id)_dataForTruncatedMessage:(id)arg1 withLength:(unsigned long long)arg2;
- (void)logMessage:(id)arg1;
- (id)initWithWriter:(id)arg1 maxLoggedBytes:(unsigned long long)arg2 maxBufferedBytes:(unsigned long long)arg3 contextInterval:(double)arg4;
- (void)dealloc;

@end