//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XCSBotConfiguration : XCSObject
{
    XCSBotSCMBlueprint *sourceControlBlueprint;
    NSString *_userDescription;
}

+ (id)botConfigurationWithSchemeName:(id)arg1 buildConfiguration:(id)arg2 overrideToolchain:(id)arg3 builtFromClean:(unsigned long long)arg4 performsAnalyzeAction:(BOOL)arg5 performsTestAction:(BOOL)arg6 performsArchiveAction:(BOOL)arg7 codeCoveragePreference:(unsigned long long)arg8 exportsProductFromArchive:(BOOL)arg9 triggers:(struct NSArray *)arg10 sourceControlBlueprint:(id)arg11 testingDestinationType:(unsigned long long)arg12 testingDeviceIDs:(id)arg13 deviceSpecification:(id)arg14 scheduleType:(unsigned long long)arg15 periodicScheduleInterval:(unsigned long long)arg16 weeklyScheduleDay:(long long)arg17 hourOfIntegration:(unsigned long long)arg18 minutesAfterHourToIntegrate:(unsigned long long)arg19 buildEnvironmentVariables:(id)arg20 validationErrors:(id *)arg21;
@property(readonly, copy) NSString *userDescription; // @synthesize userDescription=_userDescription;
@property(retain) XCSBotSCMBlueprint *sourceControlBlueprint; // @synthesize sourceControlBlueprint;
- (void).cxx_destruct;
- (BOOL)_validateSchemeName:(id)arg1 buildConfiguration:(id)arg2 overrideToolchain:(id)arg3 builtFromClean:(unsigned long long)arg4 performsAnalyzeAction:(BOOL)arg5 performsTestAction:(BOOL)arg6 performsArchiveAction:(BOOL)arg7 codeCoveragePreference:(unsigned long long)arg8 exportsProductFromArchive:(BOOL)arg9 triggers:(struct NSArray *)arg10 sourceControlBlueprint:(id)arg11 testingDestinationType:(unsigned long long)arg12 testingDeviceIDs:(id)arg13 deviceSpecification:(id)arg14 scheduleType:(unsigned long long)arg15 periodicScheduleInterval:(unsigned long long)arg16 weeklyScheduleDay:(long long)arg17 hourOfIntegration:(unsigned long long)arg18 minutesAfterHourToIntegrate:(unsigned long long)arg19 buildEnvironmentVariables:(id)arg20 validationErrors:(id *)arg21;
- (id)initWithContents:(id)arg1 service:(id)arg2 validationErrors:(id *)arg3;
- (id)initWithSchemeName:(id)arg1 buildConfiguration:(id)arg2 overrideToolchain:(id)arg3 builtFromClean:(unsigned long long)arg4 performsAnalyzeAction:(BOOL)arg5 performsTestAction:(BOOL)arg6 performsArchiveAction:(BOOL)arg7 codeCoveragePreference:(unsigned long long)arg8 exportsProductFromArchive:(BOOL)arg9 triggers:(struct NSArray *)arg10 sourceControlBlueprint:(id)arg11 testingDestinationType:(unsigned long long)arg12 testingDeviceIDs:(id)arg13 deviceSpecification:(id)arg14 scheduleType:(unsigned long long)arg15 periodicScheduleInterval:(unsigned long long)arg16 weeklyScheduleDay:(long long)arg17 hourOfIntegration:(unsigned long long)arg18 minutesAfterHourToIntegrate:(unsigned long long)arg19 buildEnvironmentVariables:(id)arg20 validationErrors:(id *)arg21;
- (id)saveRepresentationHumanReadable:(BOOL)arg1;
- (id)saveRepresentation;
- (id)dictionaryRepresentation;
- (id)description;

// Remaining properties
@property(retain) NSString *buildConfiguration; // @dynamic buildConfiguration;
@property(retain) NSDictionary *buildEnvironmentVariables; // @dynamic buildEnvironmentVariables;
@property unsigned long long builtFromClean; // @dynamic builtFromClean;
@property unsigned long long codeCoveragePreference; // @dynamic codeCoveragePreference;
@property(retain) XCSDeviceSpecification *deviceSpecification; // @dynamic deviceSpecification;
@property BOOL exportsProductFromArchive; // @dynamic exportsProductFromArchive;
@property unsigned long long hourOfIntegration; // @dynamic hourOfIntegration;
@property unsigned long long minutesAfterHourToIntegrate; // @dynamic minutesAfterHourToIntegrate;
@property(retain) XCSToolchain *overrideToolchain; // @dynamic overrideToolchain;
@property BOOL performsAnalyzeAction; // @dynamic performsAnalyzeAction;
@property BOOL performsArchiveAction; // @dynamic performsArchiveAction;
@property BOOL performsTestAction; // @dynamic performsTestAction;
@property unsigned long long periodicScheduleInterval; // @dynamic periodicScheduleInterval;
@property unsigned long long scheduleType; // @dynamic scheduleType;
@property(copy) NSString *schemeName; // @dynamic schemeName;
@property unsigned long long testingDestinationType; // @dynamic testingDestinationType;
@property(retain) NSArray *testingDeviceIDs; // @dynamic testingDeviceIDs;
@property(retain) NSArray *triggers; // @dynamic triggers;
@property long long weeklyScheduleDay; // @dynamic weeklyScheduleDay;

@end