//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XCSKeychainSupportiOS : NSObject
{
    NSMutableDictionary *keychainData;
    NSMutableDictionary *genericPasswordQuery;
    NSData *_keychainItemIdentifier;
    CDUnknownBlockType _errorHandler;
}

@property(copy) CDUnknownBlockType errorHandler; // @synthesize errorHandler=_errorHandler;
@property(retain, nonatomic) NSMutableDictionary *genericPasswordQuery; // @synthesize genericPasswordQuery;
@property(retain, nonatomic) NSMutableDictionary *keychainData; // @synthesize keychainData;
- (void).cxx_destruct;
- (void)_propagateError:(int)arg1 message:(id)arg2;
- (void)writeToKeychain;
- (id)secItemFormatToDictionary:(id)arg1;
- (id)dictionaryToSecItemFormat:(id)arg1;
- (void)resetKeychainItem;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithServiceName:(id)arg1;
- (id)init;

@end