//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface XCSLocalBot : NSObject
{
    XCSBot *_cachedBot;
    BOOL _stateChanged;
    NSArray *_fetchedIntegrations;
    XCSLocalIntegration *_runningIntegration;
    CDUnknownBlockType _botStatusChangedCallback;
    CDUnknownBlockType _botAdvisoryStatusChangedCallback;
    NSDate *_expectedStartDate;
    NSDate *_expectedCompletionDate;
    unsigned long long _buildQueuePosition;
    NSString *_currentAdvisoryMessage;
    double _aggregateProgress;
    long long _runningIntegrationStep;
    long long _runningIntegrationResult;
    XCSLocalIntegration *_newestNonPendingIntegration;
    XCSLocalIntegration *_newestCompletedIntegration;
}

+ (void)setMaxFetchedIntegrationsCacheSize:(unsigned long long)arg1;
+ (id)sharedItemWithBotName:(id)arg1 service:(id)arg2 identifier:(id)arg3 cachedBot:(id)arg4;
+ (void)initialize;
+ (id)sharedItemWithBotName:(id)arg1 service:(id)arg2 identifier:(id)arg3;
+ (id)sharedItemWithBot:(id)arg1;
@property(retain, nonatomic) XCSLocalIntegration *newestCompletedIntegration; // @synthesize newestCompletedIntegration=_newestCompletedIntegration;
@property(retain, nonatomic) XCSLocalIntegration *newestNonPendingIntegration; // @synthesize newestNonPendingIntegration=_newestNonPendingIntegration;
@property(nonatomic) BOOL stateChanged; // @synthesize stateChanged=_stateChanged;
@property(nonatomic) long long runningIntegrationResult; // @synthesize runningIntegrationResult=_runningIntegrationResult;
@property(nonatomic) long long runningIntegrationStep; // @synthesize runningIntegrationStep=_runningIntegrationStep;
@property(nonatomic) double aggregateProgress; // @synthesize aggregateProgress=_aggregateProgress;
@property(copy, nonatomic) NSString *currentAdvisoryMessage; // @synthesize currentAdvisoryMessage=_currentAdvisoryMessage;
@property(nonatomic) unsigned long long buildQueuePosition; // @synthesize buildQueuePosition=_buildQueuePosition;
@property(retain, nonatomic) NSDate *expectedCompletionDate; // @synthesize expectedCompletionDate=_expectedCompletionDate;
@property(retain, nonatomic) NSDate *expectedStartDate; // @synthesize expectedStartDate=_expectedStartDate;
@property(copy, nonatomic) CDUnknownBlockType botAdvisoryStatusChangedCallback; // @synthesize botAdvisoryStatusChangedCallback=_botAdvisoryStatusChangedCallback;
@property(copy, nonatomic) CDUnknownBlockType botStatusChangedCallback; // @synthesize botStatusChangedCallback=_botStatusChangedCallback;
@property(retain, nonatomic) XCSLocalIntegration *runningIntegration; // @synthesize runningIntegration=_runningIntegration;
@property(readonly, nonatomic) NSArray *fetchedIntegrations; // @synthesize fetchedIntegrations=_fetchedIntegrations;
- (void).cxx_destruct;
- (void)duplicateBotCompletionHandler:(CDUnknownBlockType)arg1;
- (void)integrateAndClean:(BOOL)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteBotCompletionHandler:(CDUnknownBlockType)arg1;
- (id)service;
@property(readonly, nonatomic) NSDictionary *botSCMBlueprintAsDictionary;
@property(readonly, nonatomic) NSString *serviceClientUUID;
@property(readonly, nonatomic) NSString *identifier;
@property(readonly, nonatomic) NSString *serviceDisplayName;
@property(readonly, nonatomic) NSString *name;
- (id)cachedBot;
@property(readonly, nonatomic) XCSBot *bot;
- (void)setFetchedIntegrations:(id)arg1;
- (void)_purgeIntegrations:(id)arg1;
- (void)loadMoreIntegrations:(CDUnknownBlockType)arg1;
- (void)loadMoreIntegrations:(unsigned long long)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)populateIntegrations;
@property(readonly, nonatomic) BOOL hasPendingIntegration;
@property(readonly, nonatomic) NSArray *lastTenCompletedIntegrations;
- (void)configureListeners;
- (void)_fireAdvisoryStatusUpdateCallback:(id)arg1;
- (void)_fireStatusUpdateCallback;
- (id)description;
- (void)checkForStaleIntegrations;
- (void)updateRunningIntegration:(id)arg1;
- (void)updateCachedBot:(id)arg1;
- (id)initWithBot:(id)arg1;
- (id)initWithBotName:(id)arg1 service:(id)arg2 identifier:(id)arg3 cachedBot:(id)arg4;
- (id)initWithBotName:(id)arg1 service:(id)arg2 identifier:(id)arg3;

@end