//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface NSAnimationContext (DVTNSAnimationContextAdditions)
+ (void)dvt_animated:(BOOL)arg1 block:(CDUnknownBlockType)arg2;
+ (void)dvt_nonAnimatedBlock:(CDUnknownBlockType)arg1;
@end