//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface IBSceneUpdateResult : IBObjectBasedMarshallingResult
{
    NSArray *_processingResults;
}

@property(readonly, nonatomic) NSArray *processingResults; // @synthesize processingResults=_processingResults;
- (void).cxx_destruct;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (id)initWithIdentifier:(id)arg1 archivingTranslationContext:(id)arg2 processingResults:(id)arg3;

@end