//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface SimDevicePair : NSObject <SimDeviceNotifier>
{
    BOOL _active;
    BOOL _connected;
    NSUUID *_UUID;
    SimDevice *_gizmo;
    SimDevice *_companion;
    SimDeviceSet *_deviceSet;
    NSObject<OS_dispatch_queue> *_pairingStateQueue;
    NSMutableArray *_disconnectSources;
    unsigned long long _gizmoNotificationRegID;
    unsigned long long _companionNotificationRegID;
    NSObject<OS_dispatch_queue> *_stateVariableQueue;
    SimDeviceNotificationManager *_notificationManager;
}

+ (BOOL)testPossiblePairingWithDeviceTypeA:(id)arg1 RuntimeA:(id)arg2 DeviceTypeB:(id)arg3 RuntimeB:(id)arg4 error:(id *)arg5;
+ (id)SimDevicePairWithUUID:(id)arg1 gizmo:(id)arg2 companion:(id)arg3 active:(BOOL)arg4 connected:(BOOL)arg5 deviceSet:(id)arg6;
@property(retain) SimDeviceNotificationManager *notificationManager; // @synthesize notificationManager=_notificationManager;
@property(retain) NSObject<OS_dispatch_queue> *stateVariableQueue; // @synthesize stateVariableQueue=_stateVariableQueue;
@property unsigned long long companionNotificationRegID; // @synthesize companionNotificationRegID=_companionNotificationRegID;
@property unsigned long long gizmoNotificationRegID; // @synthesize gizmoNotificationRegID=_gizmoNotificationRegID;
@property(retain) NSMutableArray *disconnectSources; // @synthesize disconnectSources=_disconnectSources;
@property(retain) NSObject<OS_dispatch_queue> *pairingStateQueue; // @synthesize pairingStateQueue=_pairingStateQueue;
@property __weak SimDeviceSet *deviceSet; // @synthesize deviceSet=_deviceSet;
@property(retain) SimDevice *companion; // @synthesize companion=_companion;
@property(retain) SimDevice *gizmo; // @synthesize gizmo=_gizmo;
@property(copy) NSUUID *UUID; // @synthesize UUID=_UUID;
- (void).cxx_destruct;
- (void)endPairedDeviceMonitoring;
- (void)ONPSQ_endPairedDeviceMonitoring;
- (void)beginPairedDeviceMonitoring;
- (void)ONPSQ_setActiveOnPairedDevices;
- (void)ONPSQ_disconnectIPCRelayOnDevices;
- (void)ONPSQ_connectIPCRelayOnDevices;
- (void)addDisconnectMonitorPort:(unsigned int)arg1;
- (void)setConnected:(BOOL)arg1;
@property(readonly) BOOL connected;
@property BOOL active;
- (void)setActiveAsyncWithCompletionQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)setActiveWithError:(id *)arg1;
- (void)handleXPCNotificationPairConnectionStateChanged:(id)arg1;
- (void)handleXPCNotificationPairSetActive:(id)arg1;
- (void)handleXPCNotification:(id)arg1;
- (void)handleXPCRequestPairSetActive:(id)arg1 peer:(id)arg2;
- (void)handleXPCRequest:(id)arg1 peer:(id)arg2;
- (id)newDevicePairNotification;
- (id)createXPCNotification:(const char *)arg1;
- (id)createXPCRequest:(const char *)arg1;
- (long long)compare:(id)arg1;
- (id)description;
- (BOOL)unregisterNotificationHandler:(unsigned long long)arg1 error:(id *)arg2;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (unsigned long long)registerNotificationHandler:(CDUnknownBlockType)arg1;
- (void)invalidate;
- (id)initWithUUID:(id)arg1 gizmo:(id)arg2 companion:(id)arg3 active:(BOOL)arg4 connected:(BOOL)arg5 deviceSet:(id)arg6;
- (id)init;

@end